version: '3'
services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - "8222:8222"
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/store-microservices-455715/imagen-regiter-ok/client-gateway  
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    # command: npm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/store-microservices-455715/imagen-regiter-ok/auth-ms     
    environment:
      # - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  product-ms:
    container_name: product-ms
    build:
      context: ./product-ms
      dockerfile: dockerfile.prod
    # depends_on:
    #   - nats-server
    image: northamerica-northeast1-docker.pkg.dev/store-microservices-455715/imagen-regiter-ok/product-ms     
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db 

  payment-ms:
    container_name: payment-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/store-microservices-455715/imagen-regiter-ok/payment-ms     
    ports:
    - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}" 
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET} 

  orders-ms:
    container_name: orders-ms
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-northeast1-docker.pkg.dev/store-microservices-455715/imagen-regiter-ok/orders-ms       
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}


 

      

    
   