version: '3'
services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - "8222:8222"
  client-gateway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  product-ms:
    build: ./product-ms
    # ports:
    #   - "3001:3001"
    volumes:
      - ./product-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db   
  orders-ms:
    container_name: orders-ms
    build: ./orders-ms
    restart: always
    # ports:
    #   - "3002:3002"
    depends_on:
      - orders-db     
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:postgres@orders-db:5432/ordersdb?schema=public
  orders-db:
    container_name: orders-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgresql:/var/lib/postgresql/data       
    ports:
      - "5432:5432"
    # command: -p 5433      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb

  payment-ms:
    container_name: payments-ms
    build: ./payments-ms
    restart: always
    ports:
    - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"     
    volumes:
    - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  auth-ms:
    container_name: auth-ms
    build: ./auth-ms
    restart: always
    # ports:
    #   - "${AUTH_MS_PORT}:${AUTH_MS_PORT}"
    command: npm run start:dev
    volumes:
      - ./auth-ms/src:/usr/src/app/src    
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222       
      

    
   